"""empty message

Revision ID: 3291b85da8b2
Revises: 8ee12b6ba070
Create Date: 2018-10-19 13:47:47.592308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3291b85da8b2'
down_revision = '8ee12b6ba070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_user_usuario', table_name='user')
    op.drop_column('user', 'usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usuario', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_usuario', 'user', ['usuario'], unique=1)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
