"""empty message

Revision ID: a74299c44013
Revises: 
Create Date: 2018-10-23 22:53:14.960944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74299c44013'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_admin', table_name='user')
    op.create_index(op.f('ix_user_admin'), 'user', ['admin'], unique=False)
    op.drop_column('user', 'usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usuario', sa.TEXT(length=64), nullable=True))
    op.drop_index(op.f('ix_user_admin'), table_name='user')
    op.create_index('ix_user_admin', 'user', ['admin'], unique=1)
    # ### end Alembic commands ###
